### ISSUE TITLE
if wrong option passed, then gr1c never returns

### ISSUE THREAD

**Issue by johnyf** [slivingston/gr1c#22]
In bb292b4a9d9d90527269637b47d99c2e2acf1e86, `gr1c --version` or `gr1c --foo` never return.

In contrast, `gr1c -foo` says `Invalid flag given. Try "-h".`. Perhaps the `--` is understood as signaling that a file name will follow. For example, `gr1c --foo boo` says `gr1c, fopen: No such file or directory`. So, it seems that the argument parser hangs, waiting for the next space, and ignores the `foo` substring.

**Comment by slivingston** [comment]
Thanks for the report. Your proposed explanation is indeed correct.

**Comment by slivingston** [comment]
This behavior also occurs with `gr1c rg` and `gr1c patch`.

**Comment by slivingston** [comment]
Note that several arguments are permitted to have trailing text, provided that it is not ambiguous with another switch. E.g., `gr1c -hhh` has the same effect as `gr1c -h`. This could be considered a feature, but for the sake of precision, I will modify `gr1c` to demand exact matches.

**Comment by johnyf** [comment]
Side comment: it would be nice to have `--version` as the long alternative of `-V`, because it is a very common option (for one, I always get it wrong with `gr1c`). For example, `pip` does so, `-V, --version`.

**Comment by slivingston** [comment]
I agree. I will add it.
