### ISSUE TITLE
Installation on 32Bit Ubuntu 14.04: lex.yy.c syntax error

### ISSUE THREAD

**Issue by LSebeke** [slivingston/gr1c#24]
During the make-step of gr1c (after successful building of CUDD 2.5.0 or 2.5.1, have not yet tried more) on a 32bit Ubuntu machine, a syntax error is found in lex.yy.c:
lex.yy.c:1647:21 error: expected expression before '/' token
     num_to_alloc = 1; // After all that talk, this was set to 1 anyways...

I am not sure if the problem really lies with the gr1c files, I am not exactly experienced with building programs from source. I am sorry if this is entirely unrelated to gr1c, but as I do not have the skills to determine the source of the problem I thought it might be a good idea to bring it up here, just to be sure.

PS: Thank you, Mr. Livingston, for providing this software for free. I feel a deep respect for individuals investing their time in such things as this.

**edit:** corrected self-induced typo in the error message

**Comment by slivingston** [comment]
Could you tell me which released version of gr1c that you are using? If you are working directly from the repository, could you tell me the commit hash?

**Comment by LSebeke** [comment]
Of course. I tried both 0.10.0 and 0.10.1, both times using the tarball.

**Comment by slivingston** [comment]
Did you modify the Makefile or take some other action to build for i686 (or i386)? The default build configuration is for x86_64. E.g., try

```sh
make cudd CUDD_XCFLAGS='-mtune=native -DHAVE_IEEE_754 -DBSD -DSIZEOF_VOID_P=4 -DSIZEOF_LONG=4'
make all CUDD_XCFLAGS='-mtune=native -DHAVE_IEEE_754 -DBSD -DSIZEOF_VOID_P=4 -DSIZEOF_LONG=4'
```
where the `make cudd` command should work if you placed the CUDD sources under the directory extern/; e.g., you can use `get-deps.sh` to achieve this.

**Comment by slivingston** [comment]
I built a binary release of 0.10.1 for Linux i686 and posted it to <http://vehicles.caltech.edu/snapshots/gr1c/>. You could try using it if building from source is not important to you. Place the executable files `gr1c`, `gr1c-patch`, `gr1c-rg`, and `autman` somewhere on your system path. E.g., to get the files and try an example,

```sh
curl -O http://vehicles.caltech.edu/snapshots/gr1c/gr1c-0.10.1-Linux_i686.tar.gz
curl -O http://vehicles.caltech.edu/snapshots/gr1c/gr1c-0.10.1-Linux_i686.tar.gz.sig
gpg --verify gpg --verify gr1c-0.10.1-Linux_i686.tar.gz.sig
tar -xzf gr1c-0.10.1-Linux_i686.tar.gz
cd gr1c-0.10.1-Linux_i686
export PATH=`pwd`:$PATH
gr1c examples/trivial.spc
```

**Comment by slivingston** [comment]
If you do not want to check my signature, you could at least check that the SHA256 hash of gr1c-0.10.1-Linux_i686.tar.gz is 2e5ac1521cb0fe67258b9d19185581b590e2d8192012b49ead77c16eea95fb56

**Comment by LSebeke** [comment]
Thank you, the binary release works like a charm. I'm not familiar yet with signature checking, but the SHA256 hash is in agreement. 

Background information, in case you would like to pursue this:
When I tried building gr1c, I had replaced the XCFLAGS in both (cudd and gr1c) Makefiles with the flags you suggested here. Other than that I followed the instructions for manual installation on http://slivingston.github.io/gr1c/md_installation.html.

Versions tried:
* gr1c-0.10.0 and 0.10.1
* cudd-2.5.0 and 2.5.1

Processor: i686 

If there is any more helpful information I could provide I'll be happy to do so!

**Comment by slivingston** [comment]
lex.yy.c is generated automatically and should not require manual editing. It would be useful for me to know:

1. which C compiler you tried and its version. E.g., `gcc --version` if using GCC. If you in doubt, you could try `cc --version`.
2. whether you used `bison` or `yacc`, and which version. E.g., `bison --version`.
3. whether you used `flex` or `lex`, and which version. E.g., `flex --version`.
4. `make --version`
5. are there any special considerations about the build environment or platform that may be relevant? E.g., were you building within a Docker container?

I have not encountered anything similar to the error that you described, and I am interested in trying to reproduce it. However, I still doubt whether it is an issue with gr1c per se.

**Comment by slivingston** [comment]
I noticed that there is a misprint in the error message of the OP: "exopected". If you copied that message verbatim (and thus did not introduce the misprint yourself), it could be indicative of an issue related to the locale. Are you using something other than a *.UTF-8 locale, e.g., as evidenced by the environment variables LC_ALL or LC_NAME ? E.g., check `echo $LC_NAME`.

**Comment by LSebeke** [comment]
Hello again. Sorry for the delay!
I introduced that typo myself and I am indeed using utf-8. Sorry for the confusion, going to edit it right away. 
Answers to your questions:
1. I am using gcc 4.8.4 as c compiler. (gcc --version gives 'gcc (Ubuntu 4.8.4-2ubuntu1~14.04) 4.8.4') 
2. I am using bison 3.0.4 (bison --version gives 'bison (GNU Bison) 3.0.4')
3. flex 2.6.0 is used
4. make --version gives 'GNU Make 3.81'
5. I don't think so, but maybe I am missing something. I grabbed a Dell Optiplex 745 minitower ([tech specs pdf](https://www.google.nl/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjv-dmohczJAhUFeA8KHekwDLcQFggfMAA&url=https%3A%2F%2Fwww.dell.com%2Fdownloads%2Fglobal%2Fproducts%2Foptix%2Fen%2Fopti_745techspecs.pdf&usg=AFQjCNFgDoTe1OtcYE4ME4bV9NvuXG1f5Q&sig2=CfylZpbdqflFZJ46WDPTxQ&bvm=bv.109332125,d.ZWU)), formated the disk, installed ubuntu 14.04 and got to work - using pip and apt-get whenever possible and followed suggestions on where and how to install necessary components.

I thought the problem might be quite simple as gcc does not seem to recognize '// After all that talk...' as a comment... (It's also the only time '//' is used to mark a comment in that file, according to grep). Seems like I was wrong. If I had more time on my hands I might have tried to find out how lex.yy.c was actually generated, but unfortunately that is not an option at the moment.

**Comment by slivingston** [comment]
I just noticed that you are using a version of flex that is different from that currently available on Ubuntu upstream repositories. I have tested with flex 2.5.35 but not 2.6.0.

Thus, one possible explanation is that the generated code from version 2.6.0 of `flex` is not standard C by including a comment of the form `//`. gr1c is configured to build as standard C, and non-standard syntax like that will lead to an error message as you received.

Moving forward, I will investigate this further for flex and possibly send a bug report to them. As for building gr1c, you could modify the Makefile by deleting `-ansi` from the `CFLAGS` variable.

**Comment by slivingston** [comment]
I just confirmed the bug in flex 1.6.0 and am creating a report for them now.

**Comment by slivingston** [comment]
http://sourceforge.net/p/flex/mailman/message/34736770/

**Comment by slivingston** [comment]
Already fixed and will appear in the next release of flex. Relevant upstream commit is [07d89829cce4527c7614a34642d4b2c2ef5d6005](https://github.com/westes/flex/commit/07d89829cce4527c7614a34642d4b2c2ef5d6005).

**Comment by slivingston** [comment]
@LSebeke Feel free to re-open if you eventually try again using a release of flex > 1.6.0 and still find errors.
